### ISSUE TITLE
LRECL and BLKSIZE options for Mainframe Files

### ISSUE THREAD

**Issue by datawarlock** [rbheemana/foop#6]
Ram - 
In the FTP process that we had used for what I am working on we had to add the LRECL for FB files and LRECL, RDW, and BLKSIZE for VB.

I think we need to account for that when the source is a mainframe.

Thoughts?

**Comment by rbheemana** [comment]
LRECL for FB files is needed
RDW for VB file will be sufficient, why do we need LRECL and BLKSIZE? 
Please let me know if I am missing anything..
